### ISSUE TITLE
Script compatibility with Dynamo catalogue

### ISSUE THREAD

**Issue by JuhaHuiskonen** [alisterburt/dynamo2m#4]
Hi, I have 200 tomograms and the corresponding models in a Dynamo catalogue. How do I produce a STAR file for multiple tomograms in a catalogue? I A Doc file is needed for the scipt - how should this be created?  Many thanks for any tips.

**Comment by JuhaHuiskonen** [comment]
Ok, it seems this can be done from Dynamo catalogue (->Crop Particles with "pick all" and "select all"). It's not necessary to crop the volumes. In particle extraction window one can activate "just report". Then "Start cropping" will produce in the new Data folder files "crop.tbl" and "indices_column20.doc" which seem to be the files needed for dynamo2warp.

**Comment by alisterburt** [comment]
Glad you got sorted!
